#!/bin/bash
source ./config

MAGICK='imagemagick'

# Optimize png tiles with optipng (true/false)?
OPTIMIZE_PNG=false

# Extra arguments for optipng.
# For example, to perform a very thorough (and
# very slow) optimization, use:
# OPTIPNG_ARGS="-o 5"
OPTIPNG_ARGS=""

# Create optimized JPEG composite tiles?
# If true, you must specify path to cjpeg binary
# (from the MozJPEG project). MozJPEG 3+ has
# some nice tricks for smoother gradients and 
# less edge artifacts.
# See: http://calendar.perfplanet.com/2014/mozjpeg-3-0/
COMPOSITE_JPEG=false
CJPEG=cjpeg
JPEG_QUALITY=90


# https://imagemagick.org/Usage/layers/

# contours
for ZDIR in $TILE_DIR/contours_mask/* ; do
  Z=`basename $ZDIR`
   for XDIR in $ZDIR/* ; do
       X=`basename $XDIR`
       OUTDIR=$TILE_DIR/contours/$Z/$X
       mkdir -pv $OUTDIR
       FILES=`basename --multiple \`ls $XDIR/*\``
       parallel $PARALLEL_ARGS \
           convert -size 256x256 xc:\\#553300 $XDIR/{1} -alpha off \
            -compose CopyOpacity -composite \
            PNG32:$OUTDIR/{1} \
            ::: $FILES
   done
done

# hillshade_imhof
for ZDIR in $TILE_DIR/hillshade/* ; do
  Z=`basename $ZDIR`
   for XDIR in $ZDIR/* ; do
       X=`basename $XDIR`
       OUTDIR=$TILE_DIR/hillshade_imhof/$Z/$X
       mkdir -pv $OUTDIR
       FILES=`basename --multiple \`ls $XDIR/*\``
       parallel --line-buffer $PARALLEL_ARGS \
          convert $XDIR/{1} -level-colors \\#404010,\\#dfdfff $OUTDIR/{1} \
          ::: $FILES
   done
done

# canopy_mask_exp
for ZDIR in $TILE_DIR/canopy_mask/* ; do
  Z=`basename $ZDIR`
   for XDIR in $ZDIR/* ; do
       X=`basename $XDIR`
       OUTDIR=$TILE_DIR/canopy_mask_exp/$Z/$X
       mkdir -pv $OUTDIR
       FILES=`basename --multiple \`ls $XDIR/*\``
       parallel $PARALLEL_ARGS \
         convert $XDIR/{1} -gamma 1.6 $OUTDIR/{1} ::: $FILES
   done
done

# baselayer
for ZDIR in $TILE_DIR/canopy_mask_exp/* ; do
  Z=`basename $ZDIR`
   for XDIR in $ZDIR/* ; do
       X=`basename $XDIR`
       OUTDIR=$TILE_DIR/baselayer/$Z/$X
       mkdir -pv $OUTDIR
       FILES=`basename --multiple \`ls $XDIR/*\``
       parallel $PARALLEL_ARGS \
         convert -size 256x256 xc:\\#eeddcc \
             xc:\\#709966 $TILE_DIR/canopy_mask_exp/$Z/$X/{1} -composite \
             \\\( $TILE_DIR/hillshade_imhof/$Z/$X/{1} -alpha set -channel A -evaluate set 30% \\\) -compose hard-light -composite \
             $TILE_DIR/contours/$Z/$X/{1} -compose src-over -composite \
             $OUTDIR/{1} \
             ::: $FILES
   done
done

# composite
for ZDIR in $TILE_DIR/baselayer/* ; do
  Z=`basename $ZDIR`
   for XDIR in $ZDIR/* ; do
       X=`basename $XDIR`
       OUTDIR=$TILE_DIR/composite/$Z/$X
       mkdir -pv $OUTDIR
       FILES=`basename --multiple \`ls $XDIR/*\``
       parallel $PARALLEL_ARGS \
           convert $TILE_DIR/baselayer/$Z/$X/{1} $TILE_DIR/features/$Z/$X/{1} \
             -compose src-over -composite $OUTDIR/{1} \
             ::: $FILES
   done
done



# Optimize PNG tiles
if $OPTIMIZE_PNG ; then
	for LAYER in contours features baselayer composite ; do
		echo "Optimizing PNG in $LAYER..."
		find $TILE_DIR/$LAYER -name "*.png" | \
			parallel -m $PARALLEL_ARGS optipng --quiet 
    done	
fi

# Create JPEG composites
if $COMPOSITE_JPEG ; then
	echo "Creating JPEG composites..."
	find $TILE_DIR/composite -name "*.png" | \
		parallel echo '{}' \; convert '{}' TGA:- \| \
		$CJPEG -sample 1x1 -quality $JPEG_QUALITY -targa \
		-outfile \`dirname '{}'\`/\`basename '{}' .png\`.jpg
fi
