#!/bin/bash
source ./config

MAGICK='imagemagick'
TILEDIR='tiles'

# https://imagemagick.org/Usage/layers/

# contours
for ZDIR in $TILEDIR/contours_mask/* ; do
  Z=`basename $ZDIR`
   for XDIR in $ZDIR/* ; do
       X=`basename $XDIR`
       OUTDIR=$TILEDIR/contours/$Z/$X
       mkdir -pv $OUTDIR
       FILES=`basename --multiple \`ls $XDIR/*\``
       parallel --line-buffer $PARALLEL_ARGS \
           convert -size 256x256 xc:\\#553300 $XDIR/{1} -alpha off \
            -compose CopyOpacity -composite \
            PNG32:$OUTDIR/{1} \
            ::: $FILES
   done
done

# hillshade_imhof
for ZDIR in $TILEDIR/hillshade/* ; do
  Z=`basename $ZDIR`
   for XDIR in $ZDIR/* ; do
       X=`basename $XDIR`
       OUTDIR=$TILEDIR/hillshade_imhof/$Z/$X
       mkdir -pv $OUTDIR
       FILES=`basename --multiple \`ls $XDIR/*\``
       parallel --line-buffer $PARALLEL_ARGS \
          convert $XDIR/{1} -level-colors \\#404010,\\#dfdfff $OUTDIR/{1} \
          ::: $FILES
   done
done

# canopy_mask_exp
for ZDIR in $TILEDIR/canopy_mask/* ; do
  Z=`basename $ZDIR`
   for XDIR in $ZDIR/* ; do
       X=`basename $XDIR`
       OUTDIR=$TILEDIR/canopy_mask_exp/$Z/$X
       mkdir -pv $OUTDIR
       FILES=`basename --multiple \`ls $XDIR/*\``
       parallel --line-buffer $PARALLEL_ARGS \
         convert $XDIR/{1} -gamma 1.6 $OUTDIR/{1} ::: $FILES
   done
done

# baselayer
for ZDIR in $TILEDIR/canopy_mask_exp/* ; do
  Z=`basename $ZDIR`
   for XDIR in $ZDIR/* ; do
       X=`basename $XDIR`
       OUTDIR=$TILEDIR/baselayer/$Z/$X
       mkdir -pv $OUTDIR
       FILES=`basename --multiple \`ls $XDIR/*\``
       parallel --line-buffer $PARALLEL_ARGS \
         convert -size 256x256 xc:\\#eeddcc \
             xc:\\#709966 $TILEDIR/canopy_mask_exp/$Z/$X/{1} -composite \
             \\\( $TILEDIR/hillshade_imhof/$Z/$X/{1} -alpha set -channel A -evaluate set 30% \\\) -compose hard-light -composite \
             $TILEDIR/contours/$Z/$X/{1} -compose src-over -composite \
             $OUTDIR/{1} \
             ::: $FILES
   done
done

# composite
for ZDIR in $TILEDIR/baselayer/* ; do
  Z=`basename $ZDIR`
   for XDIR in $ZDIR/* ; do
       X=`basename $XDIR`
       OUTDIR=$TILEDIR/composite/$Z/$X
       mkdir -pv $OUTDIR
       FILES=`basename --multiple \`ls $XDIR/*\``
       parallel --line-buffer $PARALLEL_ARGS \
           convert $TILEDIR/baselayer/$Z/$X/{1} $TILEDIR/features/$Z/$X/{1} \
             -compose src-over -composite $OUTDIR/{1} \
             ::: $FILES
   done
done
