#!/bin/bash

. config

# Railroads
echo "CREATE INDEX idx_line_rail ON ${OSM_TABLE_PREFIX}_line USING gist(way) WHERE (railway IS NOT NULL);" | $DBCMD

# Roads
echo "CREATE INDEX idx_line_roads ON ${OSM_TABLE_PREFIX}_line USING gist(way) WHERE highway IN ('motorway','trunk','primary','secondary','tertiary','residential','unclassified','service','motorway_link','primary_link','secondary_link','tertiary_link');" | $DBCMD

# Trails
echo "CREATE INDEX idx_line_trails ON ${OSM_TABLE_PREFIX}_line USING gist(way) WHERE highway IN ('track', 'bridleway', 'footway', 'path', 'pedestrian', 'cycleway');" | $DBCMD

# Coastline
echo "CREATE INDEX idx_line_coastline ON ${OSM_TABLE_PREFIX}_line USING gist(way) WHERE \"natural\" = 'coastline'" | $DBCMD

# Places
echo "CREATE INDEX idx_point_places ON ${OSM_TABLE_PREFIX}_point USING gist(way) WHERE place IS NOT NULL AND name IS NOT NULL;" | $DBCMD

# Natural
echo "CREATE INDEX idx_point_peaks ON ${OSM_TABLE_PREFIX}_point USING gist(way) WHERE \"natural\" = 'peak'" | $DBCMD

# State borders
echo "CREATE INDEX idx_line_stateborders ON ${OSM_TABLE_PREFIX}_line USING gist(way) WHERE \"boundary\" = 'administrative' AND admin_level='4'" | $DBCMD

# Parks etc
echo "CREATE INDEX idx_poly_parks ON ${OSM_TABLE_PREFIX}_polygon USING gist(way) WHERE landuse IN ('forest','vineyard','conservation','recreation_ground','village_green','cemetery') OR leisure IN ('nature_reserve','park','common','recreation_ground','playground','garden','golf course')" | $DBCMD

# Road shields/labels
# TODO
