#!/bin/bash
source ./config

# Seed script to use. Adjust e.g. to use a
# local/experimental version.
SEED=`which tilestache-seed.py`

# Extra arguments for tilestache-seed.
# For example, to force re-render of all tiles,
# use SEED_ARGS="--ignore-cached"
SEED_ARGS=""

# Layers to render (in order)
LAYERS="contours_mask hillshade canopy_mask features"

#  HACK: There seems to be a memory leak that eventually
#  makes the render run out of memory and grind to a halt.
#  Workaround: Render 1x1 degree segements at a time.
mkdir -pv "$TILE_DIR"
parallel $PARALLEL_ARGS \
	$SEED $SEED_ARGS -b {3} {2} \$[{3}+1] \$[{2}+1] \
	-c processed/tilestache.cfg \
	-d $TILE_DIR -l $LAYER {1} {4} \
	::: $LAYERS \
	::: `seq $XMIN $((XMAX-1))` \
	:::	`seq $YMIN $((YMAX-1))` \
	::: `seq $ZMIN $ZMAX`
